namespace GulpAPI.Migrations
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Migrations;
    using System.Linq;
    using GulpAPI.Models;

    internal sealed class Configuration : DbMigrationsConfiguration<GulpAPI.Models.ApplicationDbContext>
    {
        public Configuration()
        {
            AutomaticMigrationsEnabled = false;
        }

        protected override void Seed(GulpAPI.Models.ApplicationDbContext context)
        {
            context.Breweries.AddOrUpdate(x => x.Id,
                new Brewery() { Name = "10 Barrel Brewing Company", Size = "	Denver " },
new Brewery() { Name = "105 West Brewing Company", Size = "	Castle Rock " },
new Brewery() { Name = "12Degree Brewing", Size = "	Louisville " },
new Brewery() { Name = "14er Brewing Company", Size = "	Denver " },
new Brewery() { Name = "3 Freaks Brewery", Size = "	Highlands Ranch " },
new Brewery() { Name = "300 Suns Brewing", Size = "	Longmont " },
new Brewery() { Name = "38 State Brewing Company", Size = "	Littleton " },
new Brewery() { Name = "4 Noses Brewing Compan", Size = "y	Broomfield " },
new Brewery() { Name = "4B’s Brewery", Size = "	Cedaredge " },
new Brewery() { Name = "7 Hermits Brewing Company", Size = "	Eagle " },
new Brewery() { Name = "Alpine Dog Brewing Company", Size = "	Denver " },
new Brewery() { Name = "Alternation Brewing Company", Size = "	Denver " },
new Brewery() { Name = "Angry James Brewing Company", Size = "	Silverthorne " },
new Brewery() { Name = "Anheuser-Busch", Size = "	Fort Collins " },
new Brewery() { Name = "Animas Brewing Company", Size = "	Durango " },
new Brewery() { Name = "Asher Brewing Company", Size = "	Boulder " },
new Brewery() { Name = "Aspen Brewing Company", Size = "	Aspen " },
new Brewery() { Name = "Atrevida Beer Company", Size = "	Colorado Springs " },
new Brewery() { Name = "Avalanche Brewing Company", Size = "	Silverton " },
new Brewery() { Name = "Avery Brewing Company", Size = "	Boulder " },
new Brewery() { Name = "Baere Brewing Company", Size = "	Denver " },
new Brewery() { Name = "Banded Oak Brewing Company", Size = "	Denver " },
new Brewery() { Name = "Barnett & Son Brewing Company", Size = "	Parker " },
new Brewery() { Name = "Barrels & Bottles Brewery", Size = "	Golden " },
new Brewery() { Name = "Berthoud Brewing Company", Size = "	Berthoud " },
new Brewery() { Name = "Beryl’s Beer Company", Size = "	Denver " },
new Brewery() { Name = "Beyond The Mountain Brewing", Size = "	Boulder " },
new Brewery() { Name = "Bierstadt Lagerhaus", Size = "	Denver " },
new Brewery() { Name = "BierWerks Brewery", Size = "	Woodland Park " },
new Brewery() { Name = "Big Beaver Brewing Company", Size = "	Loveland" },
new Brewery() { Name = "Big Choice Brewing", Size = "	Brighton " },
new Brewery() { Name = "Big Thompson Brewery", Size = "	Loveland " },
new Brewery() { Name = "BJ’s Restaurant & Brewery", Size = " 	Boulder " },
new Brewery() { Name = "Black Bottle Brewery", Size = "	Fort Collins " },
new Brewery() { Name = "Black Forest Brewing", Size = "	Black Forest " },
new Brewery() { Name = "Black Project Spontaneous & Wild Ales", Size = "	Denver " },
new Brewery() { Name = "Black Shirt Brewing Company", Size = "	Denver " },
new Brewery() { Name = "Black Sky Brewery", Size = "	Denver " },
new Brewery() { Name = "Blue Moon Brewing Company", Size = " (RiNo)	Denver " },
new Brewery() { Name = "Blue Spruce Brewing Company", Size = "	Centennial " },
new Brewery() { Name = "Blue Spruce Brewing Company", Size = " (Littleton)	Littleton " },
new Brewery() { Name = "Blue Tile Brewing", Size = "	Denver " },
new Brewery() { Name = "Boggy Draw Brewery", Size = "	Sheridan " },
new Brewery() { Name = "Bonfire Brewing	Eagle", Size = " " },
new Brewery() { Name = "Bootstrap Brewing (Longmont)", Size = "	Longmont " },
new Brewery() { Name = "Bootstrap Brewing Company", Size = "	Niwot " },
new Brewery() { Name = "Bottom Shelf Brewery", Size = "	Bayfield " },
new Brewery() { Name = "Boulder Beer Company (The Pub On Wilderness)", Size = "	Boulder " },
new Brewery() { Name = "Brass Brewing Company", Size = "	Colorado Springs " },
new Brewery() { Name = "Breckenridge Brewery", Size = "	Littleton " },
new Brewery() { Name = "Breckenridge Brewery & Pub", Size = "	Breckenridge " },
new Brewery() { Name = "BREW Pub & Kitchen", Size = "	Durango " },
new Brewery() { Name = "Brewability Lab", Size = "	Denver " },
new Brewery() { Name = "Brewery Rickoli", Size = "	Wheat Ridge " },
new Brewery() { Name = "Brewmented", Size = "	Longmont " },
new Brewery() { Name = "Briar Common Brewery + Eatery", Size = "	Denver" },
new Brewery() { Name = "Bristol Brewing Company", Size = "	Colorado Springs" },
new Brewery() { Name = "Brix Taphouse & Brewery", Size = "	Greeley" },
new Brewery() { Name = "Broken Compass Brewery", Size = "	Breckenridge" },
new Brewery() { Name = "Broken Plow Brewery", Size = "	Greeley" },
new Brewery() { Name = "BRU Handbuilt Ales & Eats", Size = "	Boulder" },
new Brewery() { Name = "Brues Alehouse Brewing Company", Size = "	Pueblo" },
new Brewery() { Name = "Bruz Beers", Size = "	Denver" },
new Brewery() { Name = "Buckhorn Brewers", Size = "	Loveland" },
new Brewery() { Name = "Bull & Bush Pub & Brewery", Size = "	Denver" },
new Brewery() { Name = "Burly Brewing Company", Size = "	Castle Rock" },
new Brewery() { Name = "Burns Family Artisan Ales", Size = "	Denver" },
new Brewery() { Name = "Butcherknife Brewing Company", Size = "	Steamboat Springs" },
new Brewery() { Name = "Call to Arms Brewing Company", Size = "	Denver" },
new Brewery() { Name = "Cannonball Creek Brewing Company", Size = "	Golden" },
new Brewery() { Name = "Capitol Creek Brewery", Size = "	Basalt" },
new Brewery() { Name = "Carbondale Beer Works", Size = "	Carbondale" },
new Brewery() { Name = "Carver Brewing Company", Size = "	Durango" },
new Brewery() { Name = "Casey Brewing & Blending", Size = "	Glenwood Springs" },
new Brewery() { Name = "CB & Potts Restaurant & Brewery (DTC)", Size = "	Greenwood Village" },
new Brewery() { Name = "CB & Potts Restaurant & Brewery Highlands Ranch", Size = "	Highlands Ranch" },
new Brewery() { Name = "CB & Potts Restaurant & Brewery Westminster", Size = "	Westminster" },
new Brewery() { Name = "Cellar West Artisan Ales", Size = "	Boulder" },
new Brewery() { Name = "Cerberus Brewing Company", Size = "	Colorado Springs" },
new Brewery() { Name = "Cerebral Brewing", Size = "	Denver" },
new Brewery() { Name = "Cervecería Colorado", Size = "	Denver" },
new Brewery() { Name = "Chain Reaction Brewing", Size = "	Denver" },
new Brewery() { Name = "Cheluna Brewing Company", Size = "	Aurora" },
new Brewery() { Name = "City Star Brewing", Size = "	Berthoud" },
new Brewery() { Name = "CO-Brew", Size = "	Denver" },
new Brewery() { Name = "Coal Mine Ave Brewing Company", Size = "	Littleton" },
new Brewery() { Name = "Coda Brewing Company", Size = "	Golden" },
new Brewery() { Name = "Cogstone Brewing Company", Size = "	Colorado Springs" },
new Brewery() { Name = "Collision Brewing Company", Size = "	Longmont" },
new Brewery() { Name = "Colorado Boy Depot", Size = "	Ridgway" },
new Brewery() { Name = "Colorado Boy Pizzeria & Brewery", Size = "	Montrose" },
new Brewery() { Name = "Colorado Boy Pub & Brewery", Size = "	Ridgway" },
new Brewery() { Name = "Colorado Mountain Brewery", Size = "	Colorado Springs" },
new Brewery() { Name = "Colorado Mountain Brewery at the Roundhouse", Size = "	Colorado Springs" },
new Brewery() { Name = "Colorado Plus Brew Pub", Size = "Wheat Ridge" },
new Brewery() { Name = "Colorado Sake Co.", Size = "	Denver" },
new Brewery() { Name = "Comrade Brewing Company", Size = "	Denver" },
new Brewery() { Name = "CooperSmith’s Pub & Brewing Company", Size = "	Fort Collins" },
new Brewery() { Name = "Copper Club Brewing Company", Size = "	Fruita" },
new Brewery() { Name = "Copper Kettle Brewing Company", Size = "	Denver" },
new Brewery() { Name = "Crabtree Brewing Company", Size = "	Greeley" },
new Brewery() { Name = "Crafty Canary Brewery", Size = "	Walsenburg" },
new Brewery() { Name = "Crazy Mountain Brewing", Size = " Company	Denver" },
new Brewery() { Name = "Crestone Brewing Company", Size = "	Crestone" },
new Brewery() { Name = "Crooked Stave Artisan Beer Project", Size = "	Denver" },
new Brewery() { Name = "Crow Hop Brewing Company", Size = "	Loveland" },
new Brewery() { Name = "Crystal Springs Brewing Company", Size = "	Louisville" },
new Brewery() { Name = "Dad & Dude’s Breweria", Size = "	Centennial" },
new Brewery() { Name = "DC Oakes Brewhouse and Eatery", Size = "	Fort Collins" },
new Brewery() { Name = "De Steeg Brewing", Size = "	Denver" },
new Brewery() { Name = "Dead Hippie Brewing", Size = "	Sheridan" },
new Brewery() { Name = "Dean & Co Brewing", Size = "	La Junta" },
new Brewery() { Name = "Declaration Brewing", Size = "	Denver" },
new Brewery() { Name = "Denver Beer Company (Arvada)", Size = "	Arvada" },
new Brewery() { Name = "Denver Beer Company Taproom", Size = "	Denver" },
new Brewery() { Name = "Denver Chophouse & Brewery", Size = "	Denver" },
new Brewery() { Name = "Diebolt Brewing Company", Size = "	Denver" },
new Brewery() { Name = "Dillon DAM Brewery", Size = "	Dillon" },
new Brewery() { Name = "Dodgeton Creek Brewing Company", Size = "	Trinidad" },
new Brewery() { Name = "Dolores River Brewery", Size = "	Dolores" },
new Brewery() { Name = "Dos Luces", Size = "	Denver" },
new Brewery() { Name = "Dostal Alley Brewpub & Casino", Size = "	Central City" },
new Brewery() { Name = "Downhill Brewing Company", Size = "	Parker" },
new Brewery() { Name = "Dry Dock Brewing Company North", Size = "	Aurora" },
new Brewery() { Name = "Dry Dock Brewing Company South", Size = "	Aurora" },
new Brewery() { Name = "Drätz Brewing Company", Size = "	Loveland" },
new Brewery() { Name = "Dueces Wild Brewery	Colorado", Size = " Springs" },
new Brewery() { Name = "Echo Brewing Cask and Barrel", Size = "	Erie" },
new Brewery() { Name = "Echo Brewing Company", Size = "	Frederick" },
new Brewery() { Name = "Eddyline Brewery and Taproom", Size = "	Buena Vista" },
new Brewery() { Name = "El Rancho Brewing Company", Size = "	Evergreen" },
new Brewery() { Name = "Elevation Beer Company", Size = "	Poncha Springs" },
new Brewery() { Name = "Elk Avenue Brewing Company", Size = "	Crested Butte" },
new Brewery() { Name = "Endo Brewing Company", Size = "	Lafayette" },
new Brewery() { Name = "Epic Brewing Company", Size = "	Denver" },
new Brewery() { Name = "Equinox Brewing Company", Size = "	Fort Collins" },
new Brewery() { Name = "Estes Park Brewery", Size = "	Estes Park" },
new Brewery() { Name = "Evergreen Brewery", Size = "	Evergreen" },
new Brewery() { Name = "Factotum Brewhouse", Size = "	Denver" },
new Brewery() { Name = "FanDraught Sports Brewery", Size = "	Parker" },
new Brewery() { Name = "FATE Brewing Company", Size = "	Boulder" },
new Brewery() { Name = "FERMÆNTRA", Size = "	Denver" },
new Brewery() { Name = "FH Beerworks", Size = "	Colorado Springs" },
new Brewery() { Name = "Fiction Beer Company", Size = "	Denver" },
new Brewery() { Name = "Finkel & Garf Brewing Company", Size = "	Boulder" },
new Brewery() { Name = "Floodstage Ale Works", Size = "	Brighton" },
new Brewery() { Name = "Florence Brewing Company", Size = "	Florence" },
new Brewery() { Name = "Fossil Craft Beer Company", Size = "	Colorado Springs" },
new Brewery() { Name = "Frolic Brewing Company", Size = "	Westminster" },
new Brewery() { Name = "Front Range Brewing Company", Size = "	Lafayette" },
new Brewery() { Name = "Funkwerks", Size = "	Fort Collins" },
new Brewery() { Name = "Gilded Goat Brewing", Size = "	Fort Collins" },
new Brewery() { Name = "Glenwood Canyon Brewing Company", Size = "	Glenwood Springs" },
new Brewery() { Name = "Goat Patch Brewing Company", Size = "	Colorado Springs" },
new Brewery() { Name = "Gold Camp Brewing Company", Size = "	Colorado Springs" },
new Brewery() { Name = "Golden Block Brewery", Size = "	Silverton" },
new Brewery() { Name = "Golden City Brewery", Size = "	Golden" },
new Brewery() { Name = "Goldspot Brewing Company", Size = "	Denver" },
new Brewery() { Name = "Gordon Biersch Brewery Restaurant – Broomfield", Size = "	Broomfield" },
new Brewery() { Name = "Gore Range Brewery", Size = "	Edwards" },
new Brewery() { Name = "Gorilla Alchemy Brewery", Size = "	Fort Lupton" },
new Brewery() { Name = "Grand Adventure Brewing Co.", Size = "	Kremmling" },
new Brewery() { Name = "Grand Lake Brewing Tavern", Size = "	Arvada" },
new Brewery() { Name = "Grandma’s House", Size = "	Denver" },
new Brewery() { Name = "Gravity Brewing", Size = "	Louisville" },
new Brewery() { Name = "Great Divide Brewing Company", Size = "	Denver" },
new Brewery() { Name = "Great Divide Brewing: Barrel Bar", Size = "	Denver" },
new Brewery() { Name = "Great Frontier Brewing Company", Size = "	Lakewood" },
new Brewery() { Name = "Green Earth Brewing Company", Size = "	Greeley" },
new Brewery() { Name = "Green Mountain Beer Company", Size = "	Lakewood" },
new Brewery() { Name = "Grimm Brothers Brewhouse Taproom", Size = "	Loveland" },
new Brewery() { Name = "Grist Brewing Company", Size = "	Highlands Ranch" },
new Brewery() { Name = "Grist Brewing Company Lab (Lonetree)", Size = "	Lone Tree" },
new Brewery() { Name = "Großen Bart Brewery", Size = "	Longmont" },
new Brewery() { Name = "Guanella Pass Brewing Company", Size = "	Georgetown" },
new Brewery() { Name = "Gunbarrel Brewing Company", Size = "	Boulder" },
new Brewery() { Name = "Halfpenny Brewing Company", Size = "	Centennial" },
new Brewery() { Name = "Hideaway Park Brewery", Size = "	Winter Park" },
new Brewery() { Name = "High Alpine Brewing Company", Size = "	Gunnison" },
new Brewery() { Name = "High Hops Brewery", Size = "	Windsor" },
new Brewery() { Name = "HighSide Brewing", Size = "	Frisco" },
new Brewery() { Name = "Hogshead Brewery", Size = "	Denver" },
new Brewery() { Name = "Holidaily Brewing Company", Size = "	Golden" },
new Brewery() { Name = "Horse and Dragon Brewing Company", Size = "	Fort Collins" },
new Brewery() { Name = "Horsefly Brewing Company", Size = "	Montrose" },
new Brewery() { Name = "Intersect Brewing", Size = "	Fort Collins" },
new Brewery() { Name = "Iron Bird Brewing Company", Size = "	Colorado Springs" },
new Brewery() { Name = "Iron Tree Table & Taps", Size = "	Florissant" },
new Brewery() { Name = "Ironworks Brewery & Pub", Size = "	Lakewood" },
new Brewery() { Name = "J. Fargo’s Family Dining & Micro Brewery", Size = "	Cortez" },
new Brewery() { Name = "J. Moe’s Brew Pub", Size = "	Denver" },
new Brewery() { Name = "Jagged Mountain Craft Brewery", Size = "	Denver" },
new Brewery() { Name = "JAKs Brewing Company", Size = "	Falcon" },
new Brewery() { Name = "James Peak Brewery & Smokehouse", Size = "	Nederland" },
new Brewery() { Name = "Jessup Farm Barrel House", Size = "	Fort Collins" },
new Brewery() { Name = "Joyride Brewing Company", Size = "	Edgewater" },
new Brewery() { Name = "Kannah Creek Brewing Company", Size = "	Grand Junction" },
new Brewery() { Name = "Kannah Creek: Edgewater Brewery", Size = "	Grand Junction" },
new Brewery() { Name = "Kettle and Spoke Brewery", Size = "	Boulder" },
new Brewery() { Name = "Kokopelli Beer Company", Size = "	Westminster" },
new Brewery() { Name = "Lady Justice Brewing", Size = "	Denver" },
new Brewery() { Name = "Lake City Brewing Company", Size = "	Lake City" },
new Brewery() { Name = "LandLocked Ales	Lakewood", Size = "" },
new Brewery() { Name = "Lariat Lodge Brewing", Size = "	Evergreen" },
new Brewery() { Name = "Launch Pad Brewery", Size = "	Aurora" },
new Brewery() { Name = "Left Hand Brewing Company", Size = "	Longmont" },
new Brewery() { Name = "Liquid Mechanics Brewing Company", Size = "	Lafayette" },
new Brewery() { Name = "Little Machine Beer	Denver", Size = "" },
new Brewery() { Name = "Living The Dream Brewing Company", Size = "	Littleton" },
new Brewery() { Name = "Local Relic", Size = "	Colorado Springs" },
new Brewery() { Name = "Locavore Beer Works", Size = "	Littleton" },
new Brewery() { Name = "Lone Tree Brewing Company", Size = "	Lone Tree" },
new Brewery() { Name = "Long Table Brewhouse", Size = "	Denver" },
new Brewery() { Name = "Lost Highway Brewing Company", Size = "	Centennial" },
new Brewery() { Name = "Loveland Aleworks", Size = "	Loveland" },
new Brewery() { Name = "Lowdown Brewery + Kitchen", Size = "	Denver" },
new Brewery() { Name = "Lumpy Ridge Brewing Company", Size = "	Estes Park" },
new Brewery() { Name = "Mad Jack’s Mountain Brewery", Size = "	Bailey" },
new Brewery() { Name = "Mahogany Ridge Brewery and Grill", Size = "	Steamboat Springs" },
new Brewery() { Name = "Main Street Brewery & Restaurant", Size = "	Cortez" },
new Brewery() { Name = "Mancos Brewing Company", Size = "	Mancos" },
new Brewery() { Name = "Manitou Brewing Company", Size = "	Manitou Springs" },
new Brewery() { Name = "Mash Lab Brewing", Size = "	Windsor" },
new Brewery() { Name = "Maxline Brewing", Size = "	Fort Collins" },
new Brewery() { Name = "McClellan’s Brewing Company", Size = "	Fort Collins" },
new Brewery() { Name = "Metric Brewing", Size = "	Colorado Springs" },
new Brewery() { Name = "Mighty River Brewing Company", Size = "	Windsor" },
new Brewery() { Name = "MillerCoors Brewing Company", Size = "	Golden" },
new Brewery() { Name = "Mockery Brewing", Size = "	Denver" },
new Brewery() { Name = "Moonlight Pizza & Brewpub", Size = "	Salida" },
new Brewery() { Name = "Mother Tucker Brewery", Size = "	Thornton" },
new Brewery() { Name = "Mountain Cowboy Brewing Company", Size = "	Frederick" },
new Brewery() { Name = "Mountain Sun Pub & Brewery", Size = "	Boulder" },
new Brewery() { Name = "Mountain Tap Brewery", Size = "	Steamboat Springs" },
new Brewery() { Name = "Mountain Toad Brewing", Size = "	Golden" },
new Brewery() { Name = "Nano 108 Brewing Company", Size = "	Colorado Springs" },
new Brewery() { Name = "Never Summer Brewing Company", Size = "	Granby" },
new Brewery() { Name = "New Belgium Brewing Company", Size = "	Fort Collins" },
new Brewery() { Name = "New Image Brewing Company", Size = "	Arvada" },
new Brewery() { Name = "New Terrain Brewing Company", Size = "	Golden" },
new Brewery() { Name = "Novel Strand Brewing Company", Size = "	Denver" },
new Brewery() { Name = "Oasis Brewing Company", Size = "	Denver" },
new Brewery() { Name = "Odd13 Brewing", Size = "	Lafayette" },
new Brewery() { Name = "Odell Brewing – RiNo", Size = "	Denver" },
new Brewery() { Name = "Odell Brewing Company", Size = "	Fort Collins" },
new Brewery() { Name = "Odyssey Beerwerks", Size = "	Arvada" },
new Brewery() { Name = "Old Colorado Brewing Company", Size = "	Wellington" },
new Brewery() { Name = "Oskar Blues Grill & Brew", Size = "	Lyons" },
new Brewery() { Name = "Oskar Blues Tasty Weasel Taproom (Main Brewery)", Size = "	Longmont" },
new Brewery() { Name = "Our Mutual Friend Brewing Company", Size = "	Denver" },
new Brewery() { Name = "Ouray Brewery", Size = "	Ouray" },
new Brewery() { Name = "Ourayle House Brewery (Mr. Grumpy Pants)", Size = "	Ouray" },
new Brewery() { Name = "Outer Range Brewing Company", Size = "	Frisco" },
new Brewery() { Name = "Pagosa Brewing Company", Size = "	Pagosa Springs" },
new Brewery() { Name = "Palisade Brewing Company", Size = "	Palisade" },
new Brewery() { Name = "Paonia United Brewing Company", Size = "	Paonia" },
new Brewery() { Name = "Paradox Beer Company", Size = "	Divide" },
new Brewery() { Name = "Parts and Labor Brewing", Size = "	Sterling" },
new Brewery() { Name = "PDub Brewing Company", Size = "	Pueblo West" },
new Brewery() { Name = "Peak to Peak Tap & Brew", Size = "	Aurora" },
new Brewery() { Name = "Peak to Peak Tap & Brew (Colfax)", Size = "	Aurora" },
new Brewery() { Name = "Peaks N Pines Brewing Company", Size = "	Colorado Springs" },
new Brewery() { Name = "Periodic Brewing", Size = "	Leadville" },
new Brewery() { Name = "Periodic Brewing (Northglenn)", Size = "	Northglenn" },
new Brewery() { Name = "Phantom Canyon Brewing Company", Size = "	Colorado Springs" },
new Brewery() { Name = "Pikes Peak Brewing Company", Size = "	Monument" },
new Brewery() { Name = "Pilothouse Brewing Company", Size = "	Aurora" },
new Brewery() { Name = "Pints Pub Brewery & Freehouse", Size = "	Denver" },
new Brewery() { Name = "Pitchers Brewery", Size = "	Fort Collins" },
new Brewery() { Name = "Platt Park Brewing Company", Size = "	Denver" },
new Brewery() { Name = "Primitive Beer", Size = "	Longmont" },
new Brewery() { Name = "Prost Brewing Company", Size = "	Denver" },
new Brewery() { Name = "Pug Ryan’s Brewery", Size = "	Dillon" },
new Brewery() { Name = "Pumphouse Brewery", Size = "	Longmont" },
new Brewery() { Name = "Purpose Brewing and Cellars", Size = "	Fort Collins" },
new Brewery() { Name = "Rails End Beer Company", Size = "	Broomfield" },
new Brewery() { Name = "Rally King Brewing", Size = "	Fort Collins" },
new Brewery() { Name = "Ratio Beerworks", Size = "	Denver" },
new Brewery() { Name = "Red Leg Brewing Company", Size = "	Colorado Springs" },
new Brewery() { Name = "Red Mountain Brewing", Size = "	Ouray" },
new Brewery() { Name = "Red Truck Beer Company – Fort Collins", Size = "	Fort Collins" },
new Brewery() { Name = "Redgarden Restaurant and Brewery", Size = "	Louisville" },
new Brewery() { Name = "Renegade Brewing Company", Size = "	Denver" },
new Brewery() { Name = "Resolute Brewing Company", Size = "	Centennial" },
new Brewery() { Name = "Riff Raff Brewing Company", Size = "	Pagosa Springs" },
new Brewery() { Name = "River North Brewery", Size = "	Denver" },
new Brewery() { Name = "Roaring Fork Beer Company at Batch", Size = "	Carbondale" },
new Brewery() { Name = "Rock Bottom Brewery (16th St Mall – Denver)", Size = "	Denver" },
new Brewery() { Name = "Rock Bottom Brewery (Colorado Springs)", Size = "	Colorado Springs" },
new Brewery() { Name = "Rock Bottom Brewery (Highlands Ranch)", Size = "	Highlands Ranch" },
new Brewery() { Name = "Rock Bottom Brewery (Loveland)", Size = "	Loveland" },
new Brewery() { Name = "Rock Bottom Brewery (South Denver)", Size = "	Centennial" },
new Brewery() { Name = "Rock Bottom Brewery (Westminster Orchard Town Center)", Size = "	Westminster" },
new Brewery() { Name = "Rock Bottom Brewery (Westminster Promenade)", Size = "	Westminster" },
new Brewery() { Name = "Rock Coast Brewery", Size = "	Loveland" },
new Brewery() { Name = "Rock Cut Brewing Company", Size = "	Estes Park" },
new Brewery() { Name = "Rockslide Brewery & Restaurant", Size = "	Grand Junction" },
new Brewery() { Name = "Rocky Mountain Brewery", Size = "	Colorado Springs" },
new Brewery() { Name = "Rocky Mountain Taphouse", Size = "	Greeley" },
new Brewery() { Name = "Rockyard American Grill & Brewing Company", Size = "	Castle Rock" },
new Brewery() { Name = "Saint Patrick’s Brewing Company", Size = "	Littleton" },
new Brewery() { Name = "San Luis Valley Brewing Company", Size = "	Alamosa" },
new Brewery() { Name = "Sanitas Brewing Company", Size = "	Boulder" },
new Brewery() { Name = "Satire Brewing Company", Size = "	Thornton" },
new Brewery() { Name = "Seedstock Brewery", Size = "	Denver" },
new Brewery() { Name = "Shamrock Brewing Company", Size = "	Pueblo" },
new Brewery() { Name = "Shoes & Brews", Size = "	Longmont" },
new Brewery() { Name = "Ska Brewing Company", Size = "	Durango" },
new Brewery() { Name = "Smiling Toad Brewery", Size = "	Colorado Springs" },
new Brewery() { Name = "Smugglers Brewpub", Size = "	Telluride" },
new Brewery() { Name = "Snowbank Brewing", Size = "	Fort Collins" },
new Brewery() { Name = "SomePlace Else Brewery", Size = "	Arvada" },
new Brewery() { Name = "Something Brewery", Size = "	Brighton" },
new Brewery() { Name = "Soul Squared Brewing Company", Size = "	Wellington" },
new Brewery() { Name = "Soulcraft Brewing", Size = "	Salida" },
new Brewery() { Name = "South Park Brewing", Size = "	Fairplay" },
new Brewery() { Name = "Southern Sun Pub & Brewery", Size = "	Boulder" },
new Brewery() { Name = "Spangalang Brewery", Size = "	Denver" },
new Brewery() { Name = "Spice Trade Brewing Company", Size = "	Arvada" },
new Brewery() { Name = "Square Peg Brewerks", Size = "	Alamosa" },
new Brewery() { Name = "Squared Pizza + Beer", Size = "	Boulder" },
new Brewery() { Name = "Station 26 Brewing Company", Size = "	Denver" },
new Brewery() { Name = "Steamworks Brewing Company", Size = "	Durango" },
new Brewery() { Name = "Stein Brewing Company", Size = "	Boulder" },
new Brewery() { Name = "Storm Peak Brewing Company", Size = "	Steamboat Springs" },
new Brewery() { Name = "Storybook Brewing", Size = "	Colorado Springs" },
new Brewery() { Name = "Strange Craft Beer Company", Size = "	Denver" },
new Brewery() { Name = "Suds Brothers Brewery II", Size = "	Fruita" },
new Brewery() { Name = "Telluride Brewing Company", Size = "	Telluride" },
new Brewery() { Name = "The Bakers’ Brewery", Size = "	Silverthorne" },
new Brewery() { Name = "The Brew on Broadway", Size = "	Englewood" },
new Brewery() { Name = "The Colorado Farm Brewery", Size = "	Alamosa" },
new Brewery() { Name = "The Grateful Gnome Sandwich Shoppe & Brewery", Size = "	Denver" },
new Brewery() { Name = "The Industrial Revolution Brewing Company", Size = "	Erie" },
new Brewery() { Name = "The Intrepid Sojourner Beer Project", Size = "	Denver" },
new Brewery() { Name = "The Peak Bistro & Brewery", Size = "	Winter Park" },
new Brewery() { Name = "The Post Brewing Company", Size = "	Lafayette" },
new Brewery() { Name = "The Post Brewing Company (Boulder)", Size = "	Boulder" },
new Brewery() { Name = "The Sandlot Brewery", Size = "	Denver" },
new Brewery() { Name = "Thirsty Monk Brewery", Size = "	Denver" },
new Brewery() { Name = "Three Barrel Brewing Company", Size = "	Del Norte" },
new Brewery() { Name = "Tilted Barrel Brew Pub", Size = "	Loveland" },
new Brewery() { Name = "Tivoli Brewing Company", Size = "	Denver" },
new Brewery() { Name = "Tommyknocker Brewery & Pub", Size = "	Idaho Springs" },
new Brewery() { Name = "Trinity Brewing Company", Size = "	Colorado Springs" },
new Brewery() { Name = "TRVE Brewing Company", Size = "	Denver" },
new Brewery() { Name = "Tumbleweed Brewing and Wine Company", Size = "	Yuma" },
new Brewery() { Name = "Twisted Pine Brewing Company", Size = "	Boulder" },
new Brewery() { Name = "Two Rascals Brewing", Size = "	Montrose" },
new Brewery() { Name = "Two22 Brew", Size = "	Centennial" },
new Brewery() { Name = "Upslope Brewing Company Flatiron Park", Size = "	Boulder" },
new Brewery() { Name = "Upslope Brewing Company Lee Hill", Size = "	Boulder" },
new Brewery() { Name = "Ursula Brewery", Size = "	Aurora" },
new Brewery() { Name = "Ute Pass Brewing Company", Size = "	Woodland Park" },
new Brewery() { Name = "UTurn BBQ", Size = "	Lafayette" },
new Brewery() { Name = "Vail Brewing Company", Size = "	Vail" },
new Brewery() { Name = "Verboten Brewing", Size = "	Loveland" },
new Brewery() { Name = "Zwei Brewing", Size = "	Fort Collins" },
new Brewery() { Name = "Very Nice Brewing Company", Size = "	Nederland" },
new Brewery() { Name = "Veteran Brothers Brewing Company", Size = "	Johnstown" },
new Brewery() { Name = "Vine Street Pub & Brewery", Size = "	Denver" },
new Brewery() { Name = "Vision Quest Brewing Company", Size = "	Boulder" },
new Brewery() { Name = "Walter Brewing Company", Size = "	Pueblo" },
new Brewery() { Name = "WeldWerks Brewing Company", Size = "	Greeley" },
new Brewery() { Name = "West Flanders Brewing Company", Size = "	Boulder" },
new Brewery() { Name = "Westbound & Down Brewing Company", Size = "	Idaho Springs" },
new Brewery() { Name = "WestFax Brewing Company	Lakewood", Size = "" },
new Brewery() { Name = "Whistle Pig Brewing Company", Size = "	Colorado Springs" },
new Brewery() { Name = "White Labs Boulder Tasting", Size = " Room	Boulder" },
new Brewery() { Name = "Wibby Brewing", Size = "	Longmont" },
new Brewery() { Name = "Wild Woods Brewery", Size = "	Boulder" },
new Brewery() { Name = "WildEdge Brewing Collective", Size = "	Cortez" },
new Brewery() { Name = "Wiley Roots Brewing Company", Size = "	Greeley" },
new Brewery() { Name = "Wit’s End Brewing Company", Size = "	Denver" },
new Brewery() { Name = "Wonderland Brewing Company", Size = "	Broomfield" },
new Brewery() { Name = "Woods Boss Brewing", Size = "	Denver" },
new Brewery() { Name = "Wynkoop Brewing Company", Size = "	Denver" },
new Brewery() { Name = "Yampa Valley Brewing Company", Size = "	Hayden" },
new Brewery() { Name = "Zuni Street Brewing Company", Size = "	Denver" }
                );

            //  This method will be called after migrating to the latest version.

            //  You can use the DbSet<T>.AddOrUpdate() helper extension method 
            //  to avoid creating duplicate seed data.
        }
    }
}
